server:
  port: 8091
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: action-in-mybatis-plus-dev
  datasource:
    dynamic:
      enabled: true #启用动态数据源，默认true
      primary: master #设置默认的数据源或者数据源组,默认值是master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master:
          url: jdbc:mysql://localhost:3307/action-in-mybatis-plus?useSSL=false&useUnicode=true&characterSetServer=utf8mb4&serverTimezone=Asia/Shanghai
          username: action-in-mybatis-plus
          password: action-in-mybatis-plus
          driver-class-name: com.mysql.cj.jdbc.Driver
          init:  
            schema: classpath:db/schema.sql  # 建表脚本  
            data: classpath:db/data.sql      # 插入数据脚本  
            continue-on-error: false         # 是否在错误时继续  
            separator: ;                     # SQL分隔符
        slave_1:
          url: jdbc:mysql://localhost:3308/action-in-mybatis-plus?useSSL=false&useUnicode=true&characterSetServer=utf8mb4&serverTimezone=Asia/Shanghai
          username: action-in-mybatis-plus
          password: action-in-mybatis-plus
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://localhost:3309/action-in-mybatis-plus?useSSL=false&useUnicode=true&characterSetServer=utf8mb4&serverTimezone=Asia/Shanghai
          username: action-in-mybatis-plus
          password: action-in-mybatis-plus
          driver-class-name: com.mysql.cj.jdbc.Driver
  # sql:
  #   init:
  #     schema-locations: classpath:db/schema.sql
  #     data-locations: classpath:db/data.sql

logging:
  level:
    com.baomidou.dynamic.datasource: debug
    com.zaxxer.hikari: debug