server:
  port: 8091
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: action-in-mybatis-plus-dev
  datasource:
    url: jdbc:mysql://localhost:3307/action-in-mybatis-plus?useSSL=false&useUnicode=true&characterSetServer=utf8mb4&serverTimezone=Asia/Shanghai
    username: action-in-mybatis-plus
    password: action-in-mybatis-plus
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

logging:
  level:
    com.baomidou.dynamic.datasource: debug
    com.zaxxer.hikari: debug